# Generated by Django 3.0.4 on 2020-03-23 16:01

from django.db import migrations, models
import django.db.models.deletion
import guitar_tabs.models


class Migration(migrations.Migration):

    dependencies = [
        ('guitar_tabs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuitarTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_text', models.TextField()),
                ('tab_file', models.FileField(upload_to=guitar_tabs.models.user_directory_path)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitar_tabs.GuitarTabDetails')),
            ],
        ),
    ]
